#!/bin/sh
#Copyright (C) 2021  Tomás Ralph
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

chmod +x src/zerotier-gui.py
ln -sf src/zerotier-gui.py /usr/bin/zerotier-gui
mv -vf img/zerotier-gui.png /usr/share/pixmaps/
mv -vf zerotier-gui.desktop /usr/share/applications/
mv src/zerotier-gui.py .
rmdir src
mkdir -vp /usr/share/zerotier-gui
mv * /usr/share/zerotier-gui
